### ISSUE TITLE
FR : Please allow the actual Bookmarks page to show the same "scrapings" of image and/or text.

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeScraper#1]
Bookmarked Websites' thumbnails are viewable only in the river or the wall. It seems that the plugin adds "scraping" or text+small images only in the Wall or Activity stream and Activity widget. Bit the main Bookmarks page do not show these. Please allow the actual Bookmarks page - All | Mine | Friends to show the same "scrapings" of image and/or text.

**Comment by hypeJunction** [comment]
See the readme for a tip on how to achieve that.
