### ISSUE TITLE
metadata for rt.com is not being returned

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#10]
i just added rt.com to the list of sites that my site will scrape and found that no data is returned by hypescraper when the site is parsed.
the following url returns only the url and title within the 'meta' array that is used in 'src.php' in hypescraper:

```
http://rt.com/news/225355-us-drone-operator-bryant/
```

**Comment by propertunist** [comment]
i have been testing hypescraper's integration here and have found that sometimes this RT page does return all the data fields and sometimes it only returns the title and link. i'm not sure why yet.. though i did notice that, bizarrely, changing the html structure of the object that contains the outputted embed/object was enough to change whether or not the full data is rendered.

**Comment by hypeJunction** [comment]
Seems to be working fine now. I have reworked most of the parsing logic.
