### ISSUE TITLE
extractURLs is sometimes returning duplicate urls

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#12]
i have integrated hypeScraper correctly into my site so that links are automatically processed for specific views (e.g. full object views). i just came to extend the integration so that videos that are loaded on pinboard pages (from matt's au_sets plugin) are also scraped, instead of being a fixed, embedded object.
in the process of doing that, i found that the embedded objects were/are being duplicated, so that 2 embeds are added to the page, instead of one.
i thought at first that this must be a bug that i have introduced somewhere in my integration, however, once i debugged to find the cause, i found that i can pass a single youtube url into the function called 'extractURLs' and it will return an array containing 2 urls, instead of one (which is the cause of the duplication.
i don't know why this is occurring presently.

**Comment by propertunist** [comment]
ah, this is caused when the text and the href of the <a> element both contain a valid url, so they are both being extracted and returned as unique urls.
i have worked around this in my integration by setting a limit of 1 in the $vars array when i call output/url_preview

**Comment by hypeJunction** [comment]
Extractor does not care if URLs are within tags, so it gives both 'href' and tag text. I have added array_unique()
