### ISSUE TITLE
check for embed/object elements within the html field in returned metadata

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#14]
some sites include an oembed or other metadata field in their page headers which hypescraper is using to populate it's 'html' variable within the metadata array and that do not contain valid objects that can be rendered in the final page. for example, several pages i have seen hypscraper create embedded modules for, were only offering some minimal text and a broken image link from within their page header metadata and hypescraper attempted to render this (with poor results).

my only suggestion for a solution to this is to check for objects, embeds and iframes within the returned metadata and to not embed anything if none of these objects are found.

**Comment by hypeJunction** [comment]
Need some whitelisting solution...
