### ISSUE TITLE
MultiplehypeScraper 1.1.3 : links on the same page slows down the page, sometimes does not pick up or show thumbnails

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeScraper#15]
Default and plain and fresh install of Elgg 1.10.4
hypeWall 3.2.3
hypeFilestore 3.0.0
hypeScraper 1.1.3
Nothing else
Browsers - latest FF, latest Opera

Settings :Scraper Service : Native DOM parser

Problems -
1)  Page becomes too slow when there are multiple links and thumbnails
2) It does not pickup thumbnails for some uri although similar plugins elsewhere (for example http://easysocial.stackideas.com/ or https://wordpress.org/plugins/buddypress-activity-plus/screenshots/) easily picks up thumbnails, also they do not slow down the page

Most plugins (for example, easysocial above) is using cache for already posted links' thumbnails, for example 
![1](https://cloud.githubusercontent.com/assets/9887635/6794090/a66a1614-d1f3-11e4-8cfa-126b9187d78e.PNG)

**Comment by hypeJunction** [comment]
I hope I have managed to resolve most performance issue. See dev branch.
