### ISSUE TITLE
Enhancement and Usability : hypeScraper 1.1.3 : let user choose the thumbnail

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeScraper#16]
The user has no idea what thumbnail will be shown.
Most similar plugins let user choose from a series of 2 to 3 or more (10 to 15) thumbnails to be chosen from. Infact all social net scripts have this functionality either in core or as a plugin. Can we look into the inners of this , for example,
https://wordpress.org/plugins/buddypress-activity-plus/screenshots/
http://easysocial.stackideas.com
Thanks for looking into this.

**Comment by pilumati** [comment]
+1
Let the user select from a series of thumbnails, please. It helps to choose the correct thumbnail for the topic or the link.

**Comment by hypeJunction** [comment]
I have reworked the API, so this can be done in theory, but I am not going to add complexity to this plugin.
