### ISSUE TITLE
Email addresses in posts not hyper-linking correctly

### ISSUE THREAD

**Issue by dbaltozer** [hypeJunction/hypeScraper#18]
using version 1.0.0.0
Elgg version 1.8
New to the project so upgrading Elgg is not my choice.
Tried updating plugin to 1.2.0-dev18. Installs without error but front end of site goes blank.
Reverted back to 1.0.0.0. Site back working.

The issue:
The email address in group posts are not hyper-linking completely. Only the user name is clickable.
The link, on mouse over, looks like :mailto:myname. The @ symbol and domain are not included and are not highlighted blue. Example: myname@mydomain.com. Only the "myname" part is clickable.

Additionallly, not all email addresses are 'clean'.Here are two paragraphs. The first is what I entered for the post, the second is the results of the post. At the beginning of what actually got posted, notice the user name with the classes displaying, followed by a class and rel attribute, then the username again. Oddly the last instance of an email address did _not_ show the class and rel.

ORIGINAL TEXT FOR POST
myname@hotmail.com is not receiving any emails at this time. For further information please do not contact myname@hotmail.com at this time. If you would like to contact the Big Cat Vet Lounge owner please see if there may be a big cat under your house first and ask him or her. If there is not a big cat then you may email the Big Cat Vet Lounge owner at myOTHERname@gmail.com

POST AS SHOWN ON SCREEN AFTER SUBMITTING POST
myname" class="extractor-email" rel="nofollow">myname@hotmail.com is not receiving any emails at this time. For further information please do not contact myname" class="extractor-email" rel="nofollow">myname@hotmail.com at this time. If you would like to contact the Big Cat Vet Lounge owner please see if there may be a big cat under your house first and ask him or her. If there is not a big cat then you may email the Big Cat Vet Lounge owner at myOTHERname@gmail.com

**Comment by beck24** [comment]
The regex is grabbing > from the accompanying <p> of the html

Additionally - the email protocol needs the slashes to work correctly on all devices:

``` mailto:matt@mattbeckett.me``` should be ```mailto://matt@mattbeckett.me```

Finally the results of the regex should be passed through array_unique as multiple duplicate emails in a post will get repeatedly str_replaced messing everything up

**Comment by beck24** [comment]
also some emails are getting whitespace preceding them, again a better regex or they need to be trimmed before the replacement

**Comment by beck24** [comment]
Use this regex:
```const REGEX_EMAIL = "/(?:[A-Za-z0-9!#$%&'*+=?^_`{|}~-]+(?:\.[A-Za-z0-9!#$%&'*+=?^_`{|}~-]+)*|\"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*\")@(?:(?:[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[A-Za-z0-9-]*[A-Za-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/";```

**Comment by hypeJunction** [comment]
I don't see any issues now. If they persist, please reopen.
@beck24 ```mailto:``` is not a protocol, but a directive that is handled by the browser. It works with locally installed email clients.

**Comment by beck24** [comment]
You're right about the mailto, but the regex was still an issue for sure
