### ISSUE TITLE
HypeScraper version 1.2.0 white screen

### ISSUE THREAD

**Issue by merilturock** [hypeJunction/hypeScraper#19]
Dear Ismaile,
        I tried the hypescrap version 1.2 in elgg 1.9 once i activate the plugin i get a white screen all over my elgg website.

**Comment by hypeJunction** [comment]
Won't work. You need latest Elgg. Or grab 1.8 branch and see if that works

**Comment by merilturock** [comment]
K. Thank you Ismaile for your support.
