### ISSUE TITLE
things appear as blank boxes and the MySQL table  url_meta_cache remians  empty

### ISSUE THREAD

**Issue by rhisss** [hypeJunction/hypeScraper#2]
All fresh installs of Elgg 1.9.6 & hypeWall & hypeScraper. After working okay for one or two links that were posted, the links no more show thumb images or texts and appear as blank. Deactivated embed.ly and used native parser, which works but not as nice, do not fetch thumbs always. Reactivated embed.ly but things appear as blank boxes and the MySQL table ```prefix_url_meta_cache``` is persistently  EMPTY. Flushed cache and all that .... no result.

**Comment by hypeJunction** [comment]
The table is gone now. Everything is cached on the filestore.
