### ISSUE TITLE
errors when outputting cards in 1.11.2

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#20]
i am testing the latest version of hypeScraper (github master) with elgg 1.11.2 here. i am upgrading the code i was using with 1.8.x for hypeScraper in my theme which ran a custom action from javascript after page load to replace relevant links on pages with url previews.
i have tested all the ways i know to get hypeScraper to fulfill this aim and so far i have not succeeded.

presently i am seeing this in the log when i output a 'card' for common sites like 'www.google.com':
```
PHP message: PHP WARNING: 2015-06-10 15:29:26 (BST): "fwrite() expects parameter 1 to be resource, boolean given" in file /var/www/html/dev.ureka.1.11.2/engine/classes/ElggDiskFilestore.php (line 113)
PHP message: PHP WARNING: 2015-06-10 15:29:26 (BST): "fclose() expects parameter 1 to be resource, boolean given" in file /var/www/html/dev.ureka.1.11.2/engine/classes/ElggDiskFilestore.php (line 141)" while reading response header from upstream, client: 127.0.0.1, server: dev.new.ureka.org, request: "POST /action/hypeScraper/get_embed HTTP/1.1", upstream: "fastcgi://unix:/socket/php-fpm.sock:", host: "dev.new.ureka.org", referrer: "http://dev.new.ureka.org/videos/watch/8815/warning-signs-that-youre-zinc-deficient"
```

is the github master intended to be ready to use presently?

my next move will be to stop using the javascript part of the process and apply the action directly in php since the image caching might have made that approach more viable than it was in the earlier version of hypeScraper i was using in elgg 1.8.x
thanks!

**Comment by propertunist** [comment]
so after a lot of debugging this issue i now have hypescraper working as i need it to in elgg 1.11.2.
i am now using url_preview to identify urls and output cards for entities and comments.
on both my local server and remote server i found that urls were not being detected by the REGEX process and when i added elgg_dump lines into that part of the code to debug the issue, i eventually found that the urls began to be detected, even though i had not changed anything that i am aware of!
once the urls were being detected correctly, i found that the icons were not being rendered in the live site for the outputted cards. i eventually found 2 problems with the images:
1. htmlawed was stripping out the inline style tags because they were inside an elgg-output object. so i replaced that style tag with an image object instead.
2. the image object was not rendering at all and i eventually found that, most likely, htmlawed was stripping out a CDN tag that i use. so i now bypass the CDN for hypescraped images.

so finally, now i can begin testing it properly!

i haven't seen any more of the fwrite and fclose errors in logs, so i will close this ticket for now.

**Comment by hypeJunction** [comment]
I had a strange similar issue. The class is not visible, then you add a
line of debug code or anything else and it works. Must have something to do
with autoloading. Try running composer install again. I will investigate
this further

**Comment by propertunist** [comment]
hmm. i didn't use composer here at all.

**Comment by hypeJunction** [comment]
I know. I packaged it. But maybe the version had a bug or something.

**Comment by propertunist** [comment]
oh ok, i have never used composer - so i will probably be best to leave that to you. i still need to test scraper with au_sets where i previously was using it to grab video embeds for improved efficiency.. i imagine that will be broken now too. nearly done though! the caching looks great from what i have seen so far. thanks a lot :)
