### ISSUE TITLE
linkfy does not work

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#21]
i am running the linkify view in pure PHP for elgg comments and description text of objects.
when i add a comment that contains a non HTML URL, an elgg username and a hashtag - i see that none of them work properly.

the non HTML formatted URL is not detected at all.
the username is detected and made into a link, but the target of the link is incorrect: instead of 'mysite.com/profile/username', the link target is:
``` http://dev.new.ureka.org/thoughts/view/8841/profile%5C/ura_soul ```

so, the profile address is incorrectly being added to the end of the current URL.

the hashtag is detected and made into a link, but the same kind of error occurs where the URL is malformed.

**Comment by hypeJunction** [comment]
Should be fixed

**Comment by propertunist** [comment]
i just tested the master here locally and see this when i load a page:
```
 Fatal error: Class 'Guzzle\Http\Client' not found in /mysite/mod/hypeScraper/classes/hypeJunction/Scraper/Plugin.php on line 55
```

**Comment by hypeJunction** [comment]
Right, I am moving everything to composer installs, and will then build an installer plugin. In the meantime, you need to add ```"hypejunction/hypescraper": "4.*"``` to ```composer.json``` in Elgg root and run ```composer update```

**Comment by propertunist** [comment]
ok. i ran this locally (fedora 22) and it worked fine. on my live site however (fedora 20) - composer is not an available package - so i installed it manually. after running composer update - the site does load, but i am seeing an elgg error message saying: 
```
hypescraper cannot resolve composer dependencies. run composer install
```
how/where do i do that?

**Comment by propertunist** [comment]
so i ran 'composer install' in the elgg root and now i am seeing several elgg error messages on top of each other - that all say the same as the original message.

**Comment by propertunist** [comment]
right, so i have got rid of the messages temporarily by just stopping calling hypescraper in my JS.

**Comment by hypeJunction** [comment]
Strange. Do you have elgg-root/vendor/autoload.php file?

**Comment by propertunist** [comment]
yes

**Comment by hypeJunction** [comment]
Can you dump the path https://github.com/hypeJunction/hypeScraper/blob/7b93e6e37ad02d6b3008215ba4c9a2748f072ed2/lib/autoloader.php#L7 and check that the file actually exists? Maybe permissions issue?

**Comment by propertunist** [comment]
the path was correct. i think the issue may have been that some of the files were owned by root. i set all the files to be owned by my usual configuration and now the errors have stopped. :)

**Comment by propertunist** [comment]
i just tested the original linkify issue here and i am still seeing the original broken behavior. what files did you change to fix this?

**Comment by hypeJunction** [comment]
There was no issue to fix when I checked. Must be something on your end. Try wiping the directory completely, maybe some of the views are interfering.

**Comment by propertunist** [comment]
i have already wiped the whole directory here.. i just also tested this with group discussion replies as well as comments. the outcome is the same in both cases.

**Comment by hypeJunction** [comment]
Can you post a screenshot of what you see?

**Comment by propertunist** [comment]
i'm not sure there's much i can show you that will help, since all you will see in the linkified comment is:

* a URL / 'HTML A element' of my user name, which has been inserted in place of an @ symbol with my username after it.
* HTML A elements for URLs of hashtags that i have added to the comment
* a URL that i have added as text that has not been converted to an HTML A element.

if i hover over the links that have been inserted by linkify, i can see that they point to: mysite/current_page_url/correct_target_url - rather than the correct target of mysite/correct_target_url
so the target URL is being added to
