### ISSUE TITLE
add configuration options for retrieved embed videos

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#22]
i would like to enable autoplay for videos that are retrieved via hypescraper in some circumstances (and also add other options, such as html5=1 for youtube videos).
in the earlier version of hypescraper i was able to over-ride a view and add these flags manually... now though i am having difficulty locating the best way to do this. i think that the urls for the video embeds are being retrieved from the host site directly and thus are not configured in any custom way.
is there a way for me to do this simply?

**Comment by hypeJunction** [comment]
You can get retrieve all URL metadata using ```hypeScraper()->resources->get()``` (you can see what has actually be parse in a JSON file on your filestore). You can then build a custom view with those properties.

**Comment by propertunist** [comment]
ok, looking at the process more closely, i see that youtube videos are being rendered using the 'html' field of the metadata (which has the iframe already available as a string). so the only way to ammend that, that i am aware of here, is to use a regex to manually insert the extra parameters to the url of the iframe. so i'll do that, unless you have a better idea?

**Comment by propertunist** [comment]
hmm.. oh yeah, i could use a url and add my own iframe string.. lol. i am half asleep here ;)

**Comment by propertunist** [comment]
i have resolved this now by adding a regex check for youtube in the play.js file.
