### ISSUE TITLE
links for vimeo videos return vimeo logo instead of correct thumbnail image

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#23]
i haven't had a chance to investigate why this is occurring yet - but when i use hypescraper to get data for this video: https://vimeo.com/6557476
the resulting thumbnail is just a rainbow version of the vimeo logo. 
i am able to see the correct thumbnail being retrieved via videolist.

**Comment by hypeJunction** [comment]
Works fine for me.

**Comment by propertunist** [comment]
ok, yes, working here too now

**Comment by hypeJunction** [comment]
was it easy enough to get everything installed via composer?

**Comment by propertunist** [comment]
i think i answered your question here on another ticket, right?
i just came back to optimising hypescraper for vimeo and found that this original does still exist for me. if i add a link to the video in a new area in the site, then it is apparently scraped correctly and the correct image is displayed. however, i had previously added the video to a pinboard ('katalist' on my site) and it was this instance of the vimeo video (in a pinboard widget) that was showing the rainbow coloured 'vimeo' logo instead of the video thumbnail.
i thought that this might be a caching issue, so i removed the widget from the pinboard and re-added it.. but that made no difference. then i located the cached vimeo logo image in the hypescraper thumbnail cache and deleted it, thinking that hypescraper would get a new version, but that did not occur.. so now there is simply no image being displayed for the pinboard instance of the vimeo video.
any tips welcomed!

**Comment by hypeJunction** [comment]
Find the JSON file on the filestore by greping the URL, and remove it. That will force recache.

**Comment by propertunist** [comment]
i just ran this in my filestore folder and it returned nothing:
```
grep -r "https://vimeo.com/6557476"
```
is that not the correct form?

**Comment by hypeJunction** [comment]
If that's the URL you have entered...
Try looking in individual files in \1\1\scraper_cache\resources

**Comment by propertunist** [comment]
aha, ok. yes. searching for the url did not return any hits because the json files contain only encoded URLS that are different to the full, normal URL. i found the file after searching for the video title and was able to delete it and now the item is rendered correctly. thanks.
