### ISSUE TITLE
Class 'Guzzle\Http\Client' not found

### ISSUE THREAD

**Issue by nattydreadnatty** [hypeJunction/hypeScraper#25]
Hello, after installing HypeScrapr, I got this error message in all the administration of elgg:

Fatal error: Class 'Guzzle\Http\Client' not found in /mysite/mod/hypeScraper/classes/hypeJunction/Scraper/Plugin.php on line 55

My version of elgg is 1.12.

Regards,

Fred

**Comment by hypeJunction** [comment]
Use the releases tab to download the dist version of the plugin, or run composer install if you are cloning from github.

**Comment by nattydreadnatty** [comment]
Sorry but the dist version?

**Comment by hypeJunction** [comment]
Git repository does not distribute all the vendor libraries. Use the packaged version: https://github.com/hypeJunction/hypeScraper/releases

**Comment by nattydreadnatty** [comment]
ok thank you I will try that. Thank you

**Comment by nattydreadnatty** [comment]
Thank it works
