### ISSUE TITLE
specific thumbnails do not load and instead point to: /images/titel.png

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#29]
having now fixed the class loading issue i now have another issue which is that some thumbnails are not loading correctly. their path points to: https://www.mysite.org/images/titel.png

i searched for the word 'titel' in the code but didn't see a reference that caused me to think i had found the relevant one to start debugging this.

**Comment by hypeJunction** [comment]
It was probably a bad relative URL in the DOM of the page being parsed. I have reworked how thumbnails are handled, so hopefully there won't be issues like that anymore.
