### ISSUE TITLE
Improve the native DOM parser

### ISSUE THREAD

**Issue by rhisss** [hypeJunction/hypeScraper#3]
It does not alwyas display relevant thumbnail images for example gmail.com does not show thumb
but embed.ly does show. Problem with embed.ly  is its inconsistency - sometime showing thumbs sometimes not showing anything - blank rectangular boxes. Native Dom parser is consistent - only that it does not pick up images always and when it does it picks up less relevant images compared to embed.ly

**Comment by hypeJunction** [comment]
Not sure what I can do about it. If the site does not provide proper open graph tags, our options are limited.
