### ISSUE TITLE
Special chars not retrieved correctly

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeScraper#31]
Hello,
Elgg 2.2 , Hypescraper 4.2.2 and Wall 4.4.7.
When sharing links in german language on our site (english default language) Title and text's german characters are not retrieved correctly.
Ie. http://www.salto.bz/article/10082016/offenheit-ueberraschend-gross
Title is "Offenheit überraschend groß" and is shown instead "Offenheit Ã¼berraschend groÃ"

EDIT: same thing happens for italian language with accented chars.
Ie. http://www.salto.bz/article/16082016/lnceneritore-non-sara-sempre-necessario
Original is "L'inceneritore non sarà per sempre necessario" but imported as "L'inceneritore non sarÃ  per sempre necessario"

**Comment by hypeJunction** [comment]
Fixed here: https://github.com/hypeJunction/http-parser/commit/2ef2462c5ae998532be555246f7d7c00d83f4764
Will be in the next release.
