### ISSUE TITLE
When multiple links in a page, the page is very slow or WSOD

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeScraper#4]
Native DOM parser takes a long time particularly when the river/wall has multiple scrapings to do, for example, 4 or 5 web-links, some video (eg. vimeo) links - often it will show WSOD which will become corrected when hypeScraper is disabled. Iframe.ly API may have changed - cannot get it to work, embed.ly is inconsistent. Native DOM parser usually does not fail but if there are multple scrappings it will take a long, long time to load the page or give WSOD

Debug mode will show : Fatal error: Maximum execution time of xx seconds exceeded in mod\hypeScraper\vendors\guzzlehttp\guzzle\src\Guzzle\Http\Curl\CurlMulti.php on line 228

Can we do without this guzzle ? Can an admit limit be set to per page scraping so that it can just scrape the topmost three or four web links in a page so that the page is loaded fast?

**Comment by propertunist** [comment]
my solution is to store thumbnails locally (having already resized them to an appropriate size, since some images i have seen come from news media sites are 2000px!) and to also load images as placeholders for embedded objects - only loading the embedded objects once the user clicks them (as facebook and other sites would do).
in combination this will greatly improve the page load speed.

**Comment by hypeJunction** [comment]
That's a good idea. I will see what I can do about this.

**Comment by propertunist** [comment]
great! thanks :)

**Comment by dranii** [comment]
Has there been any more development on this ?
I found a good WP plugin https://wordpress.org/plugins/wp-lynx/ that:
"can contain a thumbnail image of any of the images on the linked page, plus a short excerpt from the page. The images are automatically cached on your server (no hot-linking), and the content is intelligently scraped."
This wp plugin, once the user types in the link and presses enter, is presented with a screen of thumbnails ( arrow>slide) from which the user can choose one. The image is cached so that pageload times are fast.

**Comment by propertunist** [comment]
i have not a coded anything for this issue here as i have been dealing with so many non code related life issues! i would like to have image caching implemented as some of my pages are quite slow to load. any thoughts on that @hypeJunction ?

**Comment by hypeJunction** [comment]
I don't have any time or energy at the moment.

**Comment by propertunist** [comment]
ok, no problem. i may return to this in the next 2 weeks

**Comment by hypeJunction** [comment]
Should be resolved.
