### ISSUE TITLE
Tags are not saved correctly in the database

### ISSUE THREAD

**Issue by joalbor1** [hypeJunction/hypeScraper#40]
The tags (e.g. #cat, #truck, ...) that the hypeScraper plugin parses from the text of a publication with the hypeWall plugin are stored as tags annotations but without the # symbol. This causes that when doing searches with the search plugin of Elgg does not find the labels.

I show an example in the following image.

![screenshot](https://cloud.githubusercontent.com/assets/7083393/21426981/42deec3a-c852-11e6-8f87-c97614041c21.png)

**Comment by hypeJunction** [comment]
I don't think they should be saved as tags. Feel free to change that in your action.
