### ISSUE TITLE
Hypescraper can bring entire site down

### ISSUE THREAD

**Issue by nubbyless** [hypeJunction/hypeScraper#41]
Hi I have found if you scrape this URL https://www.google.com/amp/www.dailymail.co.uk/news/article-4173342/amp/Iran-tests-ballistic-missile-violation-resolution.html?client=ms-android-verizon  it will bring the entire site down until you disable hypescraper it is the end of the URL after .Html   ?client=ms-android-verizon  that does it I tested on 4 sites running hypescraper and it crashed the entire site if you remove from the question mark on the URL scrapes fine

**Comment by nubbyless** [comment]
After more testing I may be wrong about the cause but I tested on a few more sites and brought them right down internal error 500

**Comment by nubbyless** [comment]
Seems to be an issue in parser.php Dom function around line 322  I tried an older version 4.2.2 and it did not suffer from this issue

**Comment by hypeJunction** [comment]
I don't see any issues with this URL. It scrapes fine. 
I have found an issue with relative URLs along the line. See if the latest version is fixing it for you. I have added an admin interface for previewing cards, so you don't have to take the site down to test.

**Comment by nubbyless** [comment]
The new release fixed the issues

**Comment by michelesbw** [comment]
Nice improvement, thanks!
Now wall posts can not be posted if link is unscrapable which prevents the site to crash. Just as details if you need/want to analyze, my previously mentioned link is not scraped and this neither http://www.radiomontecarlo.net/video/news/225005/alike-il-cortometraggio-che-ogni-genitore-e-ogni-bambino-dovrebbero-vedere.html#.WJW11FS0Ovw.facebook
Cheers

**Comment by michelesbw** [comment]
Hmmm actually now the site broke with that link. It seems wall post wasn't posted with error message "remote page is not accessible" and this is ok but /activity and /wall/owner pages are blank and I have no guid for the element to be deleted so...what to do?

**Comment by hypeJunction** [comment]
Making a new release. See if that helps.
