### ISSUE TITLE
[feedback] Ability to choose image when >1 on scraped site

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeScraper#44]
Very often sites have more than 1 image per page so having the possibility to choose which to scrape would be better.
Cheers :)

**Comment by hypeJunction** [comment]
It's a bit of a challenge to implement. What if the same link shared by multiple people? Who decides?

**Comment by michelesbw** [comment]
That's my point, decides who shares the link :)
I've seen other sites (don't remember which ones sorry) offering a preview of 5-6 images to choose from in a nice slideshow.
But just a feedback to eventually improve the plugin if/when you like :)

**Comment by michelesbw** [comment]
Moreover, If I like to share the same page more than once I can choose different image to make it look "new" share and possibly gain somebody else's attention

**Comment by hypeJunction** [comment]
Not sure I will ever get to it. Too much work without any gain.

**Comment by hypeJunction** [comment]
Admins will have this option in the next release.
