### ISSUE TITLE
upgrade for 2.3 fails repeatedly

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#47]
i am currently upgrading my live site to elgg 2.3 and am running the hypescraper upgrade process. i have had to reload the page and restart the upgrade process about 20 times so far because it hangs after differing amounts of time. sometimes it might process 200 items and sometimes only 5 before the hang occurs.
i am not seeing any record of an error anywhere.

**Comment by hypeJunction** [comment]
I can't tell you anything without the logs. You can just wipe the data from the data directory. Meta will be populated whenever a card is rendered

**Comment by propertunist** [comment]
ok, there's nothing in my main website php log for this at all. i am just restarting the upgrade repeatedly until it is finished. i am nearly there now.
