### ISSUE TITLE
entire elgg cache missing after upgrade! - and missing hypeScraper icons

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#48]
i have a very serious issue here and i don't know if it is related to hypescraper or not.. but here it is:
shortly after i completed the regularly breaking process of upgrading the hypscraper icons (over 3000 in total) - i noticed that all the images were missing on my site.
i found that almost all of the folders were now missing inside of my site's data folder!
the files/folders were not in the server trash and i am not aware of any process that would have deleted them. so my thought is that possibly there is a weird glitch in hypeScraper's upgrade process where accidentally it somehow deleted almost everything instead of just it's own cache. or maybe it is an elgg bug.
i have now restored the deleted files/folders from a backup, but now i see that the hypescraper thumbnails that previously were visible correctly are showing up as missing in the front end.
i extracted a URL from one of the missing images and tried to access the image directly from my server (https://www.ureka.org/serve-file/e0/l1491271208/di/c0/jMh8HqQyyisAG2u6G1A-SwCnl5vlcQ4Kj1-l6tPSTBE/1/1/scraper_cache/thumbs/e08131436c07cdd1b989a4df7771087371a39941.jpg)

and saw: HMAC mistmatch

what can i do to get the hypeScraper cache to re-initialise and/or fix this issue?

**Comment by hypeJunction** [comment]
I doubt that hypeScraper's upgrade script did anything to the data directory, but if you have any details to justify your claim, I am all ears.

If you upgraded to latest hypeScraper, you don't have to do anything. It should be able to parse all the links again. If not, just drop the contents of the scraper cache database table, and wipe the thumbnails.

**Comment by propertunist** [comment]
i don't have any details beyond what i already provided. i am not making a claim so much as just describing what i have experienced. if i find any, i will let you know.

when i reload pages with scraped content on them, they are not reloading the thumbnails. in fact, the thumbnails did initially load (from a cache, i presume) but then disappeared quickly after page load and never returned.

i have now cleared the database table and for the most part the thumbnails are now loading correctly. strangely, there is one that refuses to load - which is a youtube video that exists on youtube just like all the others.

**Comment by propertunist** [comment]
i don't have any details beyond what i already provided. i am not making a claim so much as just describing what i have experienced. if i find any, i will let you know.

when i reload pages with scraped content on them, they are not reloading the thumbnails. in fact, the thumbnails did initially load (from a cache, i presume) but then disappeared quickly after page load and never returned.

i have now cleared the database table and for the most part the thumbnails are now loading correctly. strangely, there is one that refuses to load - which is a youtube video that exists on youtube just like all the others.
