### ISSUE TITLE
feature: auto-flush

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#49]
i have setup my site so that hypescraper is used to retrieve and render youtube videos on some pages when the page contains a valid youtube URL. this generally works fine, but today i noticed that 1 specific youtube URL fails to render at all. i debugged the issue somewhat and found that i needed to set the 'flush' flag for the function hypeapps_scrape before the URL would be rendered correctly.

i initially thought it would be good to have a manual admin tool that admins can use to trigger a flush for specific urls (which would work a bit like facebook's debugger tool) - but i also notice that it should be possible to detect that no data has been returned by the scraper code and then automatically trigger a flush to see if that resolves the issue without the admin being involved.

**Comment by hypeJunction** [comment]
Empty data would in most cases indicate a non-existent or broken page. Empty values are stored in order to not waste cycles on retrying. I was going to add a way to flush manually, so I guess I'll do that

**Comment by propertunist** [comment]
the thing is that the data was populated immediately once flushed and also did not fail when i ran it on my test server, so somewhere along the line there was a failure and a flush was necessary for that url.
it would be great if you would provide a function that can be called in PHP (or even javascript) that will flush a url - so that it can be done by me as a coder or alternatively by presenting a refresh button in the UI for users in some circumstances.
