### ISSUE TITLE
add a plugin hook to facilitate scraping of custom services

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#5]
there are many sites that provide usable embeds, that do not provide info about them in the metatag fields on their pages. adding a hook to hypeScraper to allow developers to extend the code to provide support specific sites, such as liveleak.com, theguardian.com and many others is needed.

**Comment by hypeJunction** [comment]
Do you think there is a pattern I could apply to map these before running a
hook? Can you provide some link examples?

**Comment by propertunist** [comment]
i think that it would be difficult to make a generic regex that could pick out media accurately, since there are so many combinations possible and each site might implement media embeds slightly differently. i don't know of a way to identify primary media objects and miss out 'advert objects', for example.

examples:

http://www.liveleak.com/view?i=5e4_1421199532

http://www.theguardian.com/media/2015/jan/14/charlie-hebdo-issue-on-sale-paris-attacks-france-queues

both of those pages hold a primary media object and both have given different IDs to the embed code, than they did for the main page URL. so i think for these (and other) examples, there would need to be a specific function created for each of them.

i've been looking through the videolist code here and there is already a model in there for an extendable platform that supports multiple custom site definitions. i just created one for dailymotion.com - however, i found that i need to create a developer account before i can access more than the absolute basics from their API.

**Comment by propertunist** [comment]
the 'good' news is that the 300+ sites on embed.ly contains many that most are never going to want to use.

**Comment by hypeJunction** [comment]
There is now a hook that you can use to modify parsed tags.
