### ISSUE TITLE
Only the video embed works, But no cards for URLs or any other content

### ISSUE THREAD

**Issue by allux0** [hypeJunction/hypeScraper#50]
So it seems like everything is set up properly, all the plugin dependencies seem to be there and there aren't any noticeable errors but when a blog post is shared with a url in it there is no preview card. Preview cards do show up for youtube videos when you use "embed content">player.

Am I missing something? Let me know if I can provide you with any specific info to solve issue.

**Comment by hypeJunction** [comment]
There is no support for blogs. Use hypeEmbed.

**Comment by hypeJunction** [comment]
If you just add a URL to the blog body, nothing is going to happen. You need to use the embed player function in hypeEmbed, or write your own parser. https://gist.github.com/hypeJunction/522c1ea600b2a9e9382e45d7b16bb8d6
