### ISSUE TITLE
add a way to enable/disable previews for each link

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#7]
for several reasons, such as ensuring a particular text layout can be maintained - it is necessary to be able to assign some links to be replaced with a preview and some to be ignored by the preview parser.

ideally there would be a new button added to the text editors (tinymce/ckeditor) to be able to toggle previews for each link.

i imagine this could be done by adding a tag property to the <a> link and then making a plugin for the text editors that adds/removes that property from the <a> element when the element is highlighted.

**Comment by hypeJunction** [comment]
Hm. Not sure how feasible it is, given that parsed URLs have no owners. This needs to be implemented on a per instance basis. I have implemented handlers for URLs, so you can set a handler to an entity that contains the link, and then rewrite the json file on the filestore.
