### ISSUE TITLE
add autoplay option in admin settings

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#8]
for various reasons it would be helpful to have a plugin-wide option to enable autoplaying on video embeds. for one, i have created (and now testing/finishing) the process of placing a placeholder image that will be clickable (to be replaced with the embed video) and so at that point the user has already elected to access the video and so it would be right to autoplay the video.
if there is a possible way to do this without over-riding each embed object, case by case, it would be great to have.

**Comment by propertunist** [comment]
for now i have added some regexes that add on the autoplay parameters for youtube and vimeo.

**Comment by hypeJunction** [comment]
I have removed players completely. There is now a play button that loads json and replaces the view. I believe you should be able to add autoplay with JS.
